### PR TITLE
Changed schema for JSON test to be defined in a .proto file.

### PR DESCRIPTION
**Pull request by haberman**
Before we had lots of code to build these schemas manually,
but this was verbose and made it difficult to add to the
schema easily.  Now we can just write a .proto file and
adding fields is easy.

To avoid making the tests depend on upbc (and thus Lua)
we check in the generated schema.

### CODE REVIEW

**Comment by haberman** [comment]
Review to @scwhittle.

**Comment by haberman** [comment]
Tests are green, want to take a look at this one also?

**Comment by haberman** [comment]
@scwhittle.

**Comment by scwhittle** [comment]
LGTM

**Pull request merged**
